about/urls.py
from . import views
from django.urls import path
from django.conf import settings

app_name = 'about'

urlpatterns = [
    path('', views.about, name="about"),
]

contact/urls.py
from . import views
from django.urls import path


app_name = 'contact'

urlpatterns = [
    path('', views.contact, name="contact"),
]

lindhaven_coffee_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('about/', include('about.urls')),
    path('products/', include('products.urls')),
    path('contact/', include('contact.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from . import views
from django.urls import path
from django.conf import settings


app_name = 'products'

urlpatterns = [
    path('', views.products, name="products"),
]

about/models.py
from django.db import models

# Create your models here.

contact/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render

# Create your views here.


def about(request):
    return render(request, 'about/about.html')

contact/views.py
from django.shortcuts import render

# Create your views here.


def contact(request):
    return render(request, 'contact/contact.html')

home/views.py
from django.shortcuts import render

# Create your views here.


def home(request):
    return render(request, 'home/home.html')

products/views.py
from django.shortcuts import render

# Create your views here.


def products(request):
    return render(request, 'products/products.html')

about/templates/about/about.html
<h1>About</h1>

contact/templates/contact/contact.html
<h1>Contact</h1>

home/templates/home/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% load static%}
      <link rel="stylesheet" href="{% static "css/main.css"%}">
    <script src="https://kit.fontawesome.com/1cce7401dc.js" crossorigin="anonymous"></script>
    <script src="{% static 'css/javascript.js'%}" crossorigin="anonymous"></script>

    <title>Lindhaven Coffee</title>
</head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
<a class="navbar-brand" href="{% url 'home'%}"><i class="fas fa-mug-hot fa-2x"></i></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="container">
      <div class="collapse navbar-collapse justify-content-end text-uppercase font-weight-bold" id="navbar">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link m-2 menu" href="{% url 'home'%}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link m-2 menu" href="{% url 'about:about'%}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link m-2 menu" href="{% url 'products:products'%}">Products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link m-2 menu" href="{% url 'contact:contact'%}">Contact</a>
          </li>
          </li>
          <li class="nav-item">
            <a class="nav-link m-2 menu" href="#"><i class="fas fa-shopping-cart"></i></a>
          </li>
        </ul>
      </div>
    </div>
</nav>


    {% block nav %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

products/templates/products/products.html
<h1>Products</h1>